version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gocritic
    - nilerr
    - noctx
    - unconvert
    - unparam
    - misspell
    - usestdlibvars
    - errorlint
    - copyloopvar

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  misspell:
    locale: US
  errcheck:
    check-blank: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

run:
  timeout: 5m
