services:
  serve:
    build:
      context: .
      args:
        VERSION: ${VERSION:-dev}
    image: gnvipi:local
    ports:
      - "8080:8080"
    shm_size: "2gb"
    restart: unless-stopped
    command: ["-auto", "-addr", ":8080"]
    environment:
      CHROME_PROXY: ${CHROME_PROXY:-}
