package main

import (
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/router-for-me/CLIProxyAPI/v7/sdk/config"
)

// buildConfig constructs an in-memory CLIProxyAPI config with empty APIKeys
// (no inbound gateway key verification) and a temporary AuthDir.
func buildConfig(addr string) (cfg *config.Config, cfgPath string, err error) {
	host, port, err := parseListenAddr(addr)
	if err != nil {
		return nil, "", err
	}

	authDir, err := os.MkdirTemp("", "glm52-nvidia-auth-*")
	if err != nil {
		return nil, "", fmt.Errorf("auth dir: %w", err)
	}
	cfgPath = filepath.Join(authDir, "config.yaml")
	if err := os.WriteFile(cfgPath, []byte("# generated by cmd/serve; not used for API keys\n"), 0o600); err != nil {
		return nil, "", fmt.Errorf("write config stub: %w", err)
	}

	cfg = &config.Config{
		Host:    host,
		Port:    port,
		AuthDir: authDir,
		// Empty APIKeys: do not register config-access provider (no inbound key check).
		SDKConfig: config.SDKConfig{
			APIKeys: nil,
		},
	}
	cfg.RemoteManagement.DisableControlPanel = true
	cfg.RemoteManagement.DisableAutoUpdatePanel = true
	cfg.Plugins.Enabled = false
	cfg.LoggingToFile = false
	return cfg, cfgPath, nil
}

func parseListenAddr(addr string) (host string, port int, err error) {
	addr = strings.TrimSpace(addr)
	if addr == "" {
		return "", 8080, nil
	}
	// net.SplitHostPort requires [ipv6]:port; allow bare ":8080".
	if strings.HasPrefix(addr, ":") {
		p, err := strconv.Atoi(strings.TrimPrefix(addr, ":"))
		if err != nil || p <= 0 || p > 65535 {
			return "", 0, fmt.Errorf("invalid port in addr %q", addr)
		}
		return "", p, nil
	}
	h, pStr, err := net.SplitHostPort(addr)
	if err != nil {
		return "", 0, fmt.Errorf("invalid addr %q: %w", addr, err)
	}
	p, err := strconv.Atoi(pStr)
	if err != nil || p <= 0 || p > 65535 {
		return "", 0, fmt.Errorf("invalid port in addr %q", addr)
	}
	return h, p, nil
}
