// Package models holds the registry of NVIDIA build.nvidia.com playground
// models and their reverse-engineered NVCF invocation parameters.
//
// The build.nvidia.com playground calls
//
//	POST https://api.ngc.nvidia.com/v2/predict/models/{namespace}/{slug}
//	              nv-function-id: {functionID}
//	              nv-captcha-token: <hCaptcha token>
//
// Each playground model has its own {slug} and nv-function-id. The {namespace}
// is currently shared across all playground models (qc69jvmznzxy). The map
// below is generated by scripts/scrape_playground_models.py: it fetches the
// SSR-rendered model list from
//
//	https://build.nvidia.com/models?pageSize=200\
//	&filters=nimType%3Anim_type_preview%2CnimType%3Anim_type_upgrade_available
//
// parses all {publisher}/{slug} links, then probes each playground page for
// the server-rendered "nvcfFunctionId" + "namespace". Models whose playground
// page does not inline a function id are skipped.
//
// The filter URL returns only models with interactive playgrounds (preview
// status or upgrade available), so there is no need for a supplemental list.
//
// To regenerate the data, run
//
//	python3 scripts/scrape_playground_models.py > scripts/playground_models.json
//
// then refresh the Models map (the slug/namespace/functionID triple per id).
package models

import "fmt"

// Namespace is the NVCF namespace embedded in every playground predict URL.
// All known sandbox models currently share this one namespace.
const Namespace = "qc69jvmznzxy"

// ModelInfo is the per-model NVCF invocation data needed to call the
// (anonymous, hCaptcha-gated) playground predict endpoint.
type ModelInfo struct {
	// Slug is the model name segment used in the predict URL path
	// (everything after the last "/"). E.g. "glm-5.2" for "z-ai/glm-5.2".
	Slug string
	// Namespace is the NVCF namespace for this model. Currently always
	// Namespace, but kept per-model in case NVIDIA splits sandboxes.
	Namespace string
	// FunctionID is the nv-function-id header value (per-model UUID).
	FunctionID string
}

// PredictEndpoint returns the predict URL for a model info.
func (m ModelInfo) PredictEndpoint() string {
	return "https://api.ngc.nvidia.com/v2/predict/models/" + m.Namespace + "/" + m.Slug
}

// DefaultModel is the project's default playground model (kept for backward
// compatibility with pre-multi-model callers).
const DefaultModel = "z-ai/glm-5.2"

// Models is the registry of all supported build.nvidia.com playground models.
// Generated from scripts/playground_models.json via scripts/scrape_playground_models.py.
//
// Source: https://build.nvidia.com/models?pageSize=200
//          &filters=nimType%3Anim_type_preview%2CnimType%3Anim_type_upgrade_available
//
// All models in this map have been verified to inline an nvcfFunctionId that
// works with the anonymous predict endpoint. Models whose playground page
// does not inline a function id are absent (see the skipped list in the
// script output). Notable:
//
//   - moonshotai/kimi-k2.6 — playground exists but nvcfFunctionId is resolved
//     at runtime via an additional NVCF query gated behind the hCaptcha flow.
//     Skipped until runtime capture is implemented.
//
// Function ids are almost always unique per model, but NVIDIA aliases some
// backend versions to one NVCF function — e.g. nvidia/ising-calibration-1-35b-a3b
// and nvidia/ising-calibration-1.5-31b share 499210d3. That is fine: the
// predict endpoint is keyed by namespace/slug, which IS unique per registry key.
var Models = map[string]ModelInfo{
	"01-ai/yi-large":                                {Slug: "yi-large", Namespace: Namespace, FunctionID: "23bd454d-b225-49a3-8118-582a62fc51b8"},
	"abacusai/dracarys-llama-3_1-70b-instruct":      {Slug: "dracarys-llama-3_1-70b-instruct", Namespace: Namespace, FunctionID: "d27bf72f-ff2f-4443-95b4-5f06f85f72e5"},
	"bytedance/seed-oss-36b-instruct":                {Slug: "seed-oss-36b-instruct", Namespace: Namespace, FunctionID: "a29b2935-0a45-4dd8-a1e7-66f9fd5f612b"},
	"databricks/dbrx-instruct":                       {Slug: "dbrx-instruct", Namespace: Namespace, FunctionID: "3d6c2ff8-8bfc-4d10-8fd0-b7337288e869"},
	"deepseek-ai/deepseek-v4-flash":                  {Slug: "deepseek-v4-flash", Namespace: Namespace, FunctionID: "52e1ddb6-c745-4802-93f5-ba012d04c336"},
	"deepseek-ai/deepseek-v4-pro":                    {Slug: "deepseek-v4-pro", Namespace: Namespace, FunctionID: "74f02205-c7ba-438f-b81a-2537955bd7ec"},
	"google/codegemma-7b":                            {Slug: "codegemma-7b", Namespace: Namespace, FunctionID: "7dfc10a8-3cc4-448e-97c1-2213308dc222"},
	"google/diffusiongemma-26b-a4b-it":               {Slug: "diffusiongemma-26b-a4b-it", Namespace: Namespace, FunctionID: "ffd13b18-1c55-4a7a-b71a-acbfde9ce8a0"},
	"google/gemma-2-2b-it":                           {Slug: "gemma-2-2b-it", Namespace: Namespace, FunctionID: "b24f0b9b-17f0-4fbf-bbd6-1d01394652cf"},
	"google/gemma-2b":                                {Slug: "gemma-2b", Namespace: Namespace, FunctionID: "04174188-f742-4069-9e72-d77c2b77d3cb"},
	"google/gemma-3n-e2b-it":                         {Slug: "gemma-3n-e2b-it", Namespace: Namespace, FunctionID: "73a53951-edfe-4e94-89b0-7101a3ba17ee"},
	"google/gemma-3n-e4b-it":                         {Slug: "gemma-3n-e4b-it", Namespace: Namespace, FunctionID: "cff91490-4301-4338-8fc7-66d5c0f913b7"},
	"google/gemma-4-31b-it":                          {Slug: "gemma-4-31b-it", Namespace: Namespace, FunctionID: "48c619ec-c254-48da-8fcc-6ef8a04fed6e"},
	"google/recurrentgemma-2b":                       {Slug: "recurrentgemma-2b", Namespace: Namespace, FunctionID: "2f495340-a99f-4b4b-89bd-1beb003dd896"},
	"meta/llama-3.2-11b-vision-instruct":             {Slug: "llama-3.2-11b-vision-instruct", Namespace: Namespace, FunctionID: "9fa6fd04-ba2c-4bb3-90b7-ede407a9290f"},
	"meta/llama-3.2-1b-instruct":                     {Slug: "llama-3.2-1b-instruct", Namespace: Namespace, FunctionID: "d33e2ae1-8d2a-4cf8-b622-c98f8e0e550b"},
	"meta/llama-3.2-3b-instruct":                     {Slug: "llama-3.2-3b-instruct", Namespace: Namespace, FunctionID: "4f1c926f-42aa-4b52-9ac9-c2a2098e432f"},
	"meta/llama-3.2-90b-vision-instruct":             {Slug: "llama-3.2-90b-vision-instruct", Namespace: Namespace, FunctionID: "24e0c62b-f7d0-44ba-8012-012c2a1aaf31"},
	"meta/llama-3_1-70b-instruct":                    {Slug: "llama-3_1-70b-instruct", Namespace: Namespace, FunctionID: "8f723982-f99d-4978-a0cb-1334163e0e07"},
	"meta/llama-3_1-8b-instruct":                     {Slug: "llama-3_1-8b-instruct", Namespace: Namespace, FunctionID: "e62a4350-2218-4cf5-9262-112432d239f8"},
	"meta/llama-3_3-70b-instruct":                    {Slug: "llama-3_3-70b-instruct", Namespace: Namespace, FunctionID: "84eb5de1-166b-4bb4-a01b-4f51bd90aa52"},
	"meta/llama-4-maverick-17b-128e-instruct":        {Slug: "llama-4-maverick-17b-128e-instruct", Namespace: Namespace, FunctionID: "2f092df4-a732-4e88-b3a9-337829a9cde7"},
	"minimaxai/minimax-m2.7":                         {Slug: "minimax-m2.7", Namespace: Namespace, FunctionID: "3a2114b5-ba24-4540-8ceb-0cc9acc8647b"},
	"minimaxai/minimax-m3":                           {Slug: "minimax-m3", Namespace: Namespace, FunctionID: "87ea0ddc-cff1-4bca-bf8b-3bd98a35ddd0"},
	"mistralai/ministral-14b-instruct-2512":          {Slug: "ministral-14b-instruct-2512", Namespace: Namespace, FunctionID: "4c4bd074-0c4b-451b-9ae5-e55e85f28838"},
	"mistralai/mistral-medium-3.5-128b":              {Slug: "mistral-medium-3.5-128b", Namespace: Namespace, FunctionID: "2dedb559-9b17-4038-b4ad-e79e5e27d84f"},
	"mistralai/mistral-nemotron":                     {Slug: "mistral-nemotron", Namespace: Namespace, FunctionID: "f81394d8-63c0-4023-afa2-7ad11aa54ca3"},
	"mistralai/mistral-small-4-119b-2603":            {Slug: "mistral-small-4-119b-2603", Namespace: Namespace, FunctionID: "a9343856-38cc-453f-9e65-3f8c856d0555"},
	"mistralai/mixtral-8x7b-instruct":                {Slug: "mixtral-8x7b-instruct", Namespace: Namespace, FunctionID: "a1e53ece-bff4-44d1-8b13-c009e5bf47f6"},
	"nvidia/ising-calibration-1-35b-a3b":             {Slug: "ising-calibration-1-35b-a3b", Namespace: Namespace, FunctionID: "499210d3-3bf7-44bf-88b5-9460edfa8a38"},
	"nvidia/ising-calibration-1.5-31b":               {Slug: "ising-calibration-1.5-31b", Namespace: Namespace, FunctionID: "499210d3-3bf7-44bf-88b5-9460edfa8a38"},
	"nvidia/llama-3.1-nemotron-nano-vl-8b-v1":        {Slug: "llama-3.1-nemotron-nano-vl-8b-v1", Namespace: Namespace, FunctionID: "5756401f-7f6e-4a22-bb63-2afc1e1ced06"},
	"nvidia/llama-3_1-nemotron-nano-8b-v1":           {Slug: "llama-3_1-nemotron-nano-8b-v1", Namespace: Namespace, FunctionID: "07587d89-2056-4eb8-a448-4b05463d2478"},
	"nvidia/llama-3_3-nemotron-super-49b-v1":         {Slug: "llama-3_3-nemotron-super-49b-v1", Namespace: Namespace, FunctionID: "a2646582-44bd-4899-bdf4-acf8c9df702c"},
	"nvidia/llama-3_3-nemotron-super-49b-v1_5":       {Slug: "llama-3_3-nemotron-super-49b-v1_5", Namespace: Namespace, FunctionID: "50b12b3b-a571-46a3-968c-c13662f6402e"},
	"nvidia/mistral-nemo-minitron-8b-8k-instruct":    {Slug: "mistral-nemo-minitron-8b-8k-instruct", Namespace: Namespace, FunctionID: "5aa06dd2-0a02-4a5d-be4c-bf88e956965d"},
	"nvidia/nemotron-3-nano-30b-a3b":                 {Slug: "nemotron-3-nano-30b-a3b", Namespace: Namespace, FunctionID: "2b2dcd47-c858-425a-9c04-4cacf2eac993"},
	"nvidia/nemotron-3-nano-omni-30b-a3b-reasoning":  {Slug: "nemotron-3-nano-omni-30b-a3b-reasoning", Namespace: Namespace, FunctionID: "c4ed50ff-b5c3-409d-ab57-b79c33f5bb39"},
	"nvidia/nemotron-3-super-120b-a12b":              {Slug: "nemotron-3-super-120b-a12b", Namespace: Namespace, FunctionID: "ac74040f-9fc9-4c5e-ac74-279ba5161d69"},
	"nvidia/nemotron-3-ultra-550b-a55b":              {Slug: "nemotron-3-ultra-550b-a55b", Namespace: Namespace, FunctionID: "948fe171-ce7a-4332-8bc0-5e14e90259f9"},
	"nvidia/nemotron-4-340b-instruct":                {Slug: "nemotron-4-340b-instruct", Namespace: Namespace, FunctionID: "b0fcd392-e905-4ab4-8eb9-aeae95c30b37"},
	"nvidia/nemotron-mini-4b-instruct":               {Slug: "nemotron-mini-4b-instruct", Namespace: Namespace, FunctionID: "6fea1bef-f7ac-427e-8764-bb9e42bb8f60"},
	"nvidia/nemotron-nano-12b-v2-vl":                 {Slug: "nemotron-nano-12b-v2-vl", Namespace: Namespace, FunctionID: "198c1317-7594-4f5f-9292-0340bb6ee15e"},
	"nvidia/nvidia-nemotron-nano-9b-v2":              {Slug: "nvidia-nemotron-nano-9b-v2", Namespace: Namespace, FunctionID: "3fa6dcd2-7a3f-49da-8c90-2bec3f4523d9"},
	"openai/gpt-oss-120b":                            {Slug: "gpt-oss-120b", Namespace: Namespace, FunctionID: "9fcd3abb-183b-4ef0-b884-663507e5e66e"},
	"openai/gpt-oss-20b":                             {Slug: "gpt-oss-20b", Namespace: Namespace, FunctionID: "24d90582-d41c-4fc6-adc0-53c97f5a710f"},
	"poolside/laguna-xs-2.1":                         {Slug: "laguna-xs-2.1", Namespace: Namespace, FunctionID: "4a8f921c-c99d-4cde-92c1-c92ba9e4c50f"},
	"qwen/qwen3-next-80b-a3b-instruct":               {Slug: "qwen3-next-80b-a3b-instruct", Namespace: Namespace, FunctionID: "e467a0f2-c74f-4c21-8bf8-b977d7895f93"},
	"qwen/qwen3.5-397b-a17b":                         {Slug: "qwen3.5-397b-a17b", Namespace: Namespace, FunctionID: "f32596d4-0577-4a17-baf2-034515d1e457"},
	"sarvamai/sarvam-m":                              {Slug: "sarvam-m", Namespace: Namespace, FunctionID: "f798a713-1b19-41fa-9c7e-ad0d8648daef"},
	"stepfun-ai/step-3.5-flash":                      {Slug: "step-3.5-flash", Namespace: Namespace, FunctionID: "c64334de-a2b5-49bf-b477-af9d8e86af06"},
	"stepfun-ai/step-3.7-flash":                      {Slug: "step-3.7-flash", Namespace: Namespace, FunctionID: "44e35036-2c6d-43c1-b875-e48aa5bf11db"},
	"thinkingmachines/inkling":                       {Slug: "inkling", Namespace: Namespace, FunctionID: "e972e88f-cd11-45ef-86d2-6802da998eca"},
	"writer/palmyra-creative-122b":                   {Slug: "palmyra-creative-122b", Namespace: Namespace, FunctionID: "00bdd0a7-e38f-4423-9007-c4d8730a3f78"},
	"writer/palmyra-fin-70b-32k":                     {Slug: "palmyra-fin-70b-32k", Namespace: Namespace, FunctionID: "316490c6-f1ed-41f9-9da8-3fa9e885653b"},
	"writer/palmyra-med-70b":                         {Slug: "palmyra-med-70b", Namespace: Namespace, FunctionID: "aab71274-5281-4941-b0b8-20f339d1fc7e"},
	"writer/palmyra-med-70b-32k":                     {Slug: "palmyra-med-70b-32k", Namespace: Namespace, FunctionID: "d6faa974-3591-49a4-963d-97221d074b2e"},
	"z-ai/glm-5.2":                                   {Slug: "glm-5.2", Namespace: Namespace, FunctionID: "3b9748d8-1d85-40e8-8573-0eeaa63a4b63"},
	"zyphra/zamba2-7b-instruct":                      {Slug: "zamba2-7b-instruct", Namespace: Namespace, FunctionID: "8378ffb2-51b0-4140-9684-dda1889373e6"},
}

// ErrUnknownModel is returned when model is not in the registry.
type ErrUnknownModel struct{ Model string }

func (e *ErrUnknownModel) Error() string {
	return fmt.Sprintf("models: unknown playground model %q (not in registry; see scripts/scrape_playground_models.py)", e.Model)
}

// Lookup returns the ModelInfo for model, or an *ErrUnknownModel if it is not
// in the registry. The empty string resolves to DefaultModel.
func Lookup(model string) (ModelInfo, error) {
	if model == "" {
		model = DefaultModel
	}
	info, ok := Models[model]
	if !ok {
		return ModelInfo{}, &ErrUnknownModel{Model: model}
	}
	return info, nil
}
