// Package models holds the registry of NVIDIA build.nvidia.com playground
// models and their reverse-engineered NVCF invocation parameters.
//
// The build.nvidia.com playground calls
//
//	POST https://buildapi.ngc.nvidia.com/v2/predict/models/{namespace}/{slug}
//	              nv-function-id: {functionID}
//	              nv-captcha-token: <hCaptcha token>
//
// Each playground model has its own {slug} and nv-function-id. The registry is
// loaded at init time from playground_models.json (embedded in the binary),
// which is generated by scripts/scrape_playground_models.py: it fetches the
// SSR-rendered model list from
//
//	https://build.nvidia.com/models?pageSize=200\
//	&filters=nimType%3Anim_type_preview%2CnimType%3Anim_type_upgrade_available
//
// parses all {publisher}/{slug} links, then probes each playground page for
// the server-rendered "nvcfFunctionId" + "namespace". Models whose playground
// page does not inline a function id are skipped.
//
// To regenerate the data, run
//
//	python3 scripts/scrape_playground_models.py > internal/models/playground_models.json
package models

import (
	"encoding/json"
	"fmt"

	_ "embed"
)

// Namespace is the NVCF namespace embedded in every playground predict URL.
// All known sandbox models currently share this one namespace.
const Namespace = "qc69jvmznzxy"

// ModelInfo is the per-model NVCF invocation data needed to call the
// (anonymous, hCaptcha-gated) playground predict endpoint.
type ModelInfo struct {
	// Slug is the model name segment used in the predict URL path
	// (everything after the last "/"). E.g. "glm-5.2" for "z-ai/glm-5.2".
	Slug string
	// Namespace is the NVCF namespace for this model. Currently always
	// Namespace, but kept per-model in case NVIDIA splits sandboxes.
	Namespace string
	// FunctionID is the nv-function-id header value (per-model UUID).
	FunctionID string
	Capability *ModelCapability
}

type ModelCapability struct {
	ToolCalling      bool
	StructuredOutput bool
	Vision           bool
	// Reasoning tells normalizeThinking whether to wire chat_template_kwargs
	// for this model. When true and no per-model entry exists in
	// reasoningProfiles, the executor falls back to a generic effort profile
	// rather than silently dropping reasoning_effort.
	Reasoning bool
}

// PredictEndpoint returns the predict URL for a model info.
func (m ModelInfo) PredictEndpoint() string {
	return "https://buildapi.ngc.nvidia.com/v2/predict/models/" + m.Namespace + "/" + m.Slug
}

// DefaultModel is the project's default playground model (kept for backward
// compatibility with pre-multi-model callers).
const DefaultModel = "deepseek-ai/deepseek-v4-flash-0731"

// playgroundModelsFile mirrors the structure of playground_models.json.
type playgroundModelsFile struct {
	Groups []PlaygroundGroup `json:"groups"`
}

// PlaygroundGroup is the public view of one publisher block in the registry.
// Exported so cmd/serve's champion candidate sampler can iterate without
// needing to re-parse the embedded JSON.
type PlaygroundGroup struct {
	Publisher string          `json:"publisher"`
	Models    []PlaygroundRow `json:"models"`
}

// PlaygroundRow is one model entry inside a PlaygroundGroup.
type PlaygroundRow struct {
	Model      string `json:"model"`
	Slug       string `json:"slug"`
	Namespace  string `json:"namespace"`
	FunctionID string `json:"function_id"`
}

//go:embed playground_models.json
var playgroundModelsJSON []byte

// Models is the registry of all supported build.nvidia.com playground models,
// loaded from the embedded playground_models.json.
//
// Function ids are almost always unique per model, but NVIDIA aliases some
// backend versions to one NVCF function — e.g. nvidia/ising-calibration-1-35b-a3b
// and nvidia/ising-calibration-1.5-31b share 499210d3. That is fine: the
// predict endpoint is keyed by namespace/slug, which IS unique per registry key.
var Models = loadModels()

func loadModels() map[string]ModelInfo {
	var file playgroundModelsFile
	if err := json.Unmarshal(playgroundModelsJSON, &file); err != nil {
		panic(fmt.Sprintf("models: parsing embedded playground_models.json: %v", err))
	}
	m := make(map[string]ModelInfo, fileMetaCount(&file))
	for _, group := range file.Groups {
		for _, entry := range group.Models {
			ns := entry.Namespace
			if ns == "" {
				ns = Namespace
			}
			m[entry.Model] = ModelInfo{
				Slug:       entry.Slug,
				Namespace:  ns,
				FunctionID: entry.FunctionID,
				Capability: capabilityFor(entry.Model),
			}
		}
	}
	return m
}

func fileMetaCount(file *playgroundModelsFile) int {
	n := 0
	for _, g := range file.Groups {
		n += len(g.Models)
	}
	return n
}

// capabilityFor returns the capability flags for a model id. Single source of
// truth — reasoning.go's normalizeThinking reads this to decide whether a
// model without a per-model entry in reasoningProfiles still gets the
// generic effort-based profile.
//
// Currently only moonshotai/kimi-k3 is marked Reasoning: Kimi-k3 takes the
// standard reasoning_effort kwarg, so it just needs the generic fallback.
func capabilityFor(model string) *ModelCapability {
	switch model {
	case "moonshotai/kimi-k3":
		return &ModelCapability{Reasoning: true}
	}
	return nil
}

// AllGroups returns the parsed registry structure for callers that need
// publisher/slug pairs (e.g. cmd/serve's champion sampler). The result
// is a copy so callers can sort / shuffle without mutating package state.
func AllGroups() []PlaygroundGroup {
	var file playgroundModelsFile
	if err := json.Unmarshal(playgroundModelsJSON, &file); err != nil {
		return nil
	}
	return file.Groups
}

// ErrUnknownModel is returned when model is not in the registry.
type ErrUnknownModel struct{ Model string }

func (e *ErrUnknownModel) Error() string {
	return fmt.Sprintf("models: unknown playground model %q (not in registry; see scripts/scrape_playground_models.py)", e.Model)
}

// Lookup returns the ModelInfo for model, or an *ErrUnknownModel if it is not
// in the registry. The empty string resolves to DefaultModel.
func Lookup(model string) (ModelInfo, error) {
	if model == "" {
		model = DefaultModel
	}
	info, ok := Models[model]
	if !ok {
		return ModelInfo{}, &ErrUnknownModel{Model: model}
	}
	return info, nil
}
