// Package gnvipi provides a Go client for the NVIDIA Playground-hosted GLM-5.2 model.
// It calls the Playground predict endpoint with an hCaptcha token generated by the browser.
//
// Usage:
//
//	client := gnvipi.New(gnvipi.WithCaptchaToken("P1_..."))
//
//	// Simple chat
//	resp, _ := client.Chat(ctx, []Message{{Role: "user", Content: "Hi"}})
//	fmt.Println(resp.Choices[0].Message.Content)
//
//	// Streaming chat
//	client.StreamChat(ctx, []Message{{Role: "user", Content: "Hi"}},
//	    func(chunk StreamChunk) { fmt.Print(chunk.Content) })
package gnvipi

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/minhhhduc/gnvipi/internal/models"
)

// --- constants ---

const (
	// DefaultModel is the GLM-5.2 model identifier used by NVIDIA NIM.
	DefaultModel = "z-ai/glm-5.2"

	// PredictEndpoint is the reverse-engineered Playground API endpoint.
	PredictEndpoint = "https://buildapi.ngc.nvidia.com/v2/predict/models/qc69jvmznzxy/glm-5.2"

	// NVFunctionID is the static NVCF function identifier for GLM-5.2.
	NVFunctionID = "3b9748d8-1d85-40e8-8573-0eeaa63a4b63"

	defaultMaxTokens = 16384
	defaultSeed      = 42
	defaultTemp      = 1.0
	defaultTopP      = 1.0
	requestTimeout   = 120 * time.Second
)

// --- types ---

// Role constants.
const (
	RoleSystem    = "system"
	RoleUser      = "user"
	RoleAssistant = "assistant"
	RoleContext   = "context"
)

// Message represents a single chat message.
// When Thinking is enabled, assistant deltas/messages may include ReasoningContent.
// Upstream may send JSON null for Content or ReasoningContent; that unmarshals to "".
type Message struct {
	Role             string `json:"role,omitempty"`
	Content          string `json:"content,omitempty"`
	ReasoningContent string `json:"reasoning_content,omitempty"`
}

// ChatRequest is the request body sent to the predict API.
type ChatRequest struct {
	Model       string    `json:"model"`
	Messages    []Message `json:"messages"`
	Temperature float64   `json:"temperature,omitempty"`
	TopP        float64   `json:"top_p,omitempty"`
	MaxTokens   int       `json:"max_tokens,omitempty"`
	Seed        int       `json:"seed,omitempty"`
	Stream      bool      `json:"stream,omitempty"`

	// Extra body for NVIDIA-specific features (thinking, etc.).
	ChatTemplateKwargs map[string]any `json:"chat_template_kwargs,omitempty"`
	StreamOptions      *StreamOptions `json:"stream_options,omitempty"`
}

// StreamOptions controls SSE streaming metadata.
type StreamOptions struct {
	IncludeUsage         bool `json:"include_usage"`
	ContinuousUsageStats bool `json:"continuous_usage_stats"`
}

// ChatResponse is the non-streaming response (also used as final assembled result).
// Field set matches NVIDIA playground predict (OpenAI chat.completion shape).
type ChatResponse struct {
	ID                string   `json:"id"`
	Object            string   `json:"object"`
	Created           int64    `json:"created"`
	Model             string   `json:"model"`
	Choices           []Choice `json:"choices"`
	Usage             *Usage   `json:"usage,omitempty"`
	SystemFingerprint string   `json:"system_fingerprint,omitempty"`
	ServiceTier       string   `json:"service_tier,omitempty"`
}

// Choice is a single completion choice.
type Choice struct {
	Index        int     `json:"index"`
	Message      Message `json:"message"`
	FinishReason string  `json:"finish_reason"`
	// Logprobs is opaque; upstream currently returns null.
	Logprobs any `json:"logprobs,omitempty"`
}

// PromptTokensDetails is nested under usage when the backend reports prompt breakdowns.
// Observed on cache hits: {"audio_tokens":null,"cached_tokens":N}.
type PromptTokensDetails struct {
	CachedTokens *int `json:"cached_tokens"`
	AudioTokens  *int `json:"audio_tokens"`
}

// Usage contains token usage stats from upstream predict responses.
type Usage struct {
	PromptTokens        int                  `json:"prompt_tokens"`
	CompletionTokens    int                  `json:"completion_tokens"`
	TotalTokens         int                  `json:"total_tokens"`
	PromptTokensDetails *PromptTokensDetails `json:"prompt_tokens_details,omitempty"`
}

// CachedTokens returns prompt cache hit count when prompt_tokens_details.cached_tokens is set.
func (u *Usage) CachedTokens() int {
	if u == nil || u.PromptTokensDetails == nil || u.PromptTokensDetails.CachedTokens == nil {
		return 0
	}
	return *u.PromptTokensDetails.CachedTokens
}

// Format returns a compact human-readable usage line for CLI display.
func (u *Usage) Format() string {
	if u == nil {
		return ""
	}
	var b strings.Builder
	fmt.Fprintf(&b, "%d prompt + %d completion = %d total",
		u.PromptTokens, u.CompletionTokens, u.TotalTokens)
	if c := u.CachedTokens(); c > 0 {
		b.WriteString(" (cached ")
		b.WriteString(strconv.Itoa(c))
		b.WriteByte(')')
	} else if u.PromptTokensDetails != nil && u.PromptTokensDetails.CachedTokens != nil {
		b.WriteString(" (cached 0)")
	}
	return b.String()
}

// ChatChunk is a single SSE data chunk (streaming).
// Object is typically "chat.completion.chunk". Final usage-only chunks may have empty Choices.
type ChatChunk struct {
	ID                string        `json:"id"`
	Object            string        `json:"object"`
	Created           int64         `json:"created"`
	Model             string        `json:"model"`
	Choices           []ChunkChoice `json:"choices"`
	Usage             *Usage        `json:"usage,omitempty"`
	SystemFingerprint string        `json:"system_fingerprint,omitempty"`
	ServiceTier       string        `json:"service_tier,omitempty"`
}

// ChunkChoice is a delta choice for streaming.
type ChunkChoice struct {
	Index        int     `json:"index"`
	Delta        Message `json:"delta"`
	FinishReason string  `json:"finish_reason"`
	// Logprobs is opaque; upstream currently returns null.
	Logprobs any `json:"logprobs,omitempty"`
}

// ErrorResponse represents an API error.
type ErrorResponse struct {
	RequestStatus struct {
		StatusCode        string `json:"statusCode"`
		StatusDescription string `json:"statusDescription"`
		RequestID         string `json:"requestId"`
	} `json:"requestStatus"`
}

func (e *ErrorResponse) Error() string {
	return e.RequestStatus.StatusDescription
}

// --- Client ---

// Client is the NVIDIA Playground API client.
type Client struct {
	captchaToken string // reverse-engineered captcha token

	// HTTP client (can be overridden)
	httpClient *http.Client

	// default request parameters
	model     string
	maxTokens int
	seed      int
	temp      float64
	topP      float64

	// thinking mirrors Playground: chat_template_kwargs.enable_thinking
	thinking *bool
}

// Option configures the Client.
type Option func(*Client)

// WithCaptchaToken sets the hCaptcha token for the reverse-engineered endpoint.
// Obtain this from the Playground page: widget's data-hcaptcha-response attribute.
func WithCaptchaToken(token string) Option {
	return func(c *Client) { c.captchaToken = token }
}

// WithHTTPClient overrides the default HTTP client.
func WithHTTPClient(hc *http.Client) Option {
	return func(c *Client) { c.httpClient = hc }
}

// WithModel overrides the model name.
func WithModel(m string) Option {
	return func(c *Client) { c.model = m }
}

// WithDefaults sets default request parameters.
func WithDefaults(maxTokens int, seed int, temp, topP float64) Option {
	return func(c *Client) {
		c.maxTokens = maxTokens
		c.seed = seed
		c.temp = temp
		c.topP = topP
	}
}

// WithThinking enables or disables Thinking mode (reasoning_content).
// Matches NVIDIA Playground / NIM: chat_template_kwargs.enable_thinking.
// Default when unset: enabled (true), clear_thinking=false.
func WithThinking(enable bool) Option {
	return func(c *Client) { c.thinking = &enable }
}

// New creates a new NVIDIA Playground client configured with an hCaptcha token.
func New(opts ...Option) *Client {
	c := &Client{
		httpClient: &http.Client{Timeout: requestTimeout},
		model:      DefaultModel,
		maxTokens:  defaultMaxTokens,
		seed:       defaultSeed,
		temp:       defaultTemp,
		topP:       defaultTopP,
	}
	for _, o := range opts {
		o(c)
	}
	return c
}

// --- internal request helpers ---

func (c *Client) buildRequest(ctx context.Context, req *ChatRequest) (*http.Request, error) {
	model := req.Model
	if model == "" {
		model = c.model
	}
	info, err := models.Lookup(model)
	if err != nil {
		return nil, fmt.Errorf("gnvipi: %w", err)
	}

	body, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("gnvipi: marshal request: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", info.PredictEndpoint(), bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("gnvipi: create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("accept", "text/event-stream")
	httpReq.Header.Set("nv-function-id", info.FunctionID)
	httpReq.Header.Set("nv-captcha-token", c.captchaToken)
	httpReq.Header.Set("Origin", "https://build.nvidia.com")
	httpReq.Header.Set("Referer", "https://build.nvidia.com/")

	return httpReq, nil
}

func (c *Client) applyDefaults(r *ChatRequest) {
	if r.Model == "" {
		r.Model = c.model
	}
	if r.MaxTokens == 0 {
		r.MaxTokens = c.maxTokens
	}
	if r.Seed == 0 {
		r.Seed = c.seed
	}
	if r.Temperature == 0 {
		r.Temperature = c.temp
	}
	if r.TopP == 0 {
		r.TopP = c.topP
	}
	if len(r.ChatTemplateKwargs) == 0 {
		enable := true
		if c.thinking != nil {
			enable = *c.thinking
		}
		if enable {
			r.ChatTemplateKwargs = map[string]any{
				"enable_thinking": true,
				"clear_thinking":  false,
			}
		}
	}
}

// --- Public API ---

// Chat sends a synchronous chat completion request.
func (c *Client) Chat(ctx context.Context, messages []Message) (*ChatResponse, error) {
	req := &ChatRequest{
		Messages: messages,
		Stream:   false,
	}
	c.applyDefaults(req)

	var resp ChatResponse
	if err := c.doRequest(ctx, req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// StreamChunk is yielded by StreamChat.
type StreamChunk struct {
	Content   string
	Reasoning string // delta.reasoning_content when Thinking is on
	Usage     *Usage
	Done      bool
	Error     error
}

// StreamChat sends a streaming chat completion. Each chunk is delivered to the callback.
// The callback's return value controls whether streaming continues (true = continue).
func (c *Client) StreamChat(ctx context.Context, messages []Message, cb func(StreamChunk)) error {
	req := &ChatRequest{
		Messages: messages,
		Stream:   true,
		StreamOptions: &StreamOptions{
			IncludeUsage:         true,
			ContinuousUsageStats: false, // usage once at end — less payload / cleaner clients
		},
	}
	c.applyDefaults(req)

	return c.doStream(ctx, req, cb)
}

// --- Internal: doRequest (non-streaming) ---

func (c *Client) doRequest(ctx context.Context, req *ChatRequest, target interface{}) error {
	httpReq, err := c.buildRequest(ctx, req)
	if err != nil {
		return err
	}

	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return fmt.Errorf("gnvipi: http do: %w", err)
	}
	defer resp.Body.Close()

	// Read full body
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("gnvipi: read body: %w", err)
	}

	if resp.StatusCode >= 400 {
		return parseError(raw)
	}

	if err := json.Unmarshal(raw, target); err != nil {
		return fmt.Errorf("gnvipi: decode response: %w", err)
	}
	return nil
}

// --- Internal: doStream (SSE streaming) ---

func (c *Client) doStream(ctx context.Context, req *ChatRequest, cb func(StreamChunk)) error {
	httpReq, err := c.buildRequest(ctx, req)
	if err != nil {
		return err
	}

	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return fmt.Errorf("gnvipi: http do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		raw, _ := io.ReadAll(resp.Body)
		return parseError(raw)
	}

	// Read SSE stream
	reader := bufio.NewReader(resp.Body)
	for {
		line, err := reader.ReadString('\n')
		if err != nil {
			if err == io.EOF {
				cb(StreamChunk{Done: true})
				return nil
			}
			return fmt.Errorf("gnvipi: read sse: %w", err)
		}

		line = strings.TrimSpace(line)

		// Skip empty lines / comments
		if line == "" || strings.HasPrefix(line, ":") {
			continue
		}

		// data: [DONE]
		if line == "data: [DONE]" {
			cb(StreamChunk{Done: true})
			return nil
		}

		// data: {...}
		if strings.HasPrefix(line, "data: ") {
			data := strings.TrimPrefix(line, "data: ")
			var chunk ChatChunk
			if err := json.Unmarshal([]byte(data), &chunk); err != nil {
				cb(StreamChunk{Error: fmt.Errorf("gnvipi: decode chunk: %w", err)})
				continue
			}

			sc := StreamChunk{}
			if len(chunk.Choices) > 0 {
				sc.Content = chunk.Choices[0].Delta.Content
				sc.Reasoning = chunk.Choices[0].Delta.ReasoningContent
			}
			if chunk.Usage != nil {
				sc.Usage = chunk.Usage
			}
			cb(sc)
		}
	}
}

// --- helpers ---

func parseError(raw []byte) error {
	var apiErr ErrorResponse
	if err := json.Unmarshal(raw, &apiErr); err == nil && apiErr.RequestStatus.StatusCode != "" {
		return &apiErr
	}
	// Try OpenAI error format
	var oaiErr struct {
		Error struct {
			Message string `json:"message"`
			Type    string `json:"type"`
		} `json:"error"`
	}
	if err := json.Unmarshal(raw, &oaiErr); err == nil && oaiErr.Error.Message != "" {
		return fmt.Errorf("gnvipi: %s: %s", oaiErr.Error.Type, oaiErr.Error.Message)
	}
	return fmt.Errorf("gnvipi: http error: %s", string(raw[:min(len(raw), 300)]))
}
